image: circutor/runner_base:v3

default:
  tags:
    - docker_aws


before_script:
  - echo "List files:" && ls -l
  - echo "User:" && whoami
  - echo "IDs:" && id
  - echo "Hostname:" && hostname
  - echo "Current directory:" && pwd

stages:
  - build


build-pytoolkit:
  stage: build
  script:
    - apt-get update && apt-get install -y build-essential
    - make build-pytoolkit
    - make push-pytoolkit
  only:
    changes:
      - app/*
      - app/*/*
      - deployment/docker/pyingestiontoolkit.dockerfile
      - deployment/k8s/base/psrecorder
