
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescale-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale
spec:
  selector:
    matchLabels:
      app: timescale
  template:
    metadata:
      labels:
        app: timescale
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg12
        env:
          - name: POSTGRES_PASSWORD
            value: admin
        ports:
          - name: timescale
            containerPort: 5432
        volumeMounts:
        - name: timescale-persistent-storage
          mountPath: /var/lib/postgresql/volum
      volumes:
        - name: timescale-persistent-storage
          persistentVolumeClaim:
            claimName: timescale-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: timescale-service
spec:
  type: ClusterIP
  selector:
    app: timescale
  ports:
    - name: timescale
      port: 5432
      targetPort: timescale