apiVersion: apps/v1
kind: Deployment
metadata:
  name: psrecorder
spec:
  template:
    spec:
      containers:
      - name: psrecorder
        image: 224392328862.dkr.ecr.eu-west-1.amazonaws.com/pyingestiontoolkit:1.0
